apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  namespace: argocd
type: Opaque
stringData:
  password: Z2hwX25XeXVUb3hvQ1g0SDV5d3RQd2t4VHdRTTRPQ3dZdzBTQ0FtQg==
  username: S2EjYW4vbW50R2l0
  url: https://github.com/rajcsingh-git/argocd-app-config.git

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  resource.compareoptions: |
    ignoreResourceStatusField: all

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rajcsingh-git/test-argo.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true