apiVersion: v1
data:
  repositories: |
    - url: https://github.com/rajcsingh-git/argocd-app-config.git
      type: git
      passwordSecret:
        key: password
        name: argocd-secret
      usernameSecret:
        key: username
        name: argocd-secret
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
